added link, target.txt and proper config structure

diff --git a/link b/link
--- a/link
+++ b/link
@@ -31,6 +31,52 @@ pickHost() {
     echo "Error: There is no configuration matching this host"
     exit 1
   fi
+  if [ $host = "laptop" ]; then
+    mkdir -p $PROGRAM_TARGET
+    if [ ! -d "$SCRIPT_PATH/laptop" ]; then
+      echo "Error: The files for this configuration are missing"
+      exit 1
+    fi
+    stow -d $SCRIPT_PATH/default $PROGRAM_NAME -t $PROGRAM_TARGET
+    stow -d $SCRIPT_PATH/laptop $PROGRAM_NAME -t $PROGRAM_TARGET
+
+    if [ $? -eq 0 ]; then
+      echo "Successfully created symbolic links for the $PROGRAM_NAME package"
+      echo "    - The configuration is $host"
+      echo "    - The target is $PROGRAM_TARGET"
+    else
+      echo "Error: Failed to create symbolic links in configuration $host"
+      exit 1
+    fi
+
+    exit 0
+  else
+    echo "Error: There is no configuration matching this host"
+    exit 1
+  fi
+  if [ $host = "desktop" ]; then
+    mkdir -p $PROGRAM_TARGET
+    if [ ! -d "$SCRIPT_PATH/desktop" ]; then
+      echo "Error: The files for this configuration are missing"
+      exit 1
+    fi
+    stow -d $SCRIPT_PATH/default $PROGRAM_NAME -t $PROGRAM_TARGET
+    stow -d $SCRIPT_PATH/desktop $PROGRAM_NAME -t $PROGRAM_TARGET
+
+    if [ $? -eq 0 ]; then
+      echo "Successfully created symbolic links for the $PROGRAM_NAME package"
+      echo "    - The configuration is $host"
+      echo "    - The target is $PROGRAM_TARGET"
+    else
+      echo "Error: Failed to create symbolic links in configuration $host"
+      exit 1
+    fi
+
+    exit 0
+  else
+    echo "Error: There is no configuration matching this host"
+    exit 1
+  fi
 }
 
 deletePackage() {
